name: "Determine Environment"
description: "Determine the environment based on the service name and the branch name"

inputs:
  service_name:
    description: "The name of the service"
    required: true

runs:
  using: composite
  steps:
    - name: Determine Environment
      shell: bash
      id: set-env
      run: |
        if [ "${{ github.ref_name}}" == "main" ]; then
          echo "repo=prod-registry" >> "$GITHUB_OUTPUT"
          echo "image=prod-${{ inputs.service_name }}" >> "$GITHUB_OUTPUT"

        elif [ "${{ github.ref_name}}" == "dev" ]; then
          echo "repo=dev-registry" >> "$GITHUB_OUTPUT"
          echo "image=dev-${{ inputs.service_name }}" >> "$GITHUB_OUTPUT"

        else
          echo "Unexpected branch name: ${{ github.ref_name }}, failing the job"
          exit 1
        fi
          
outputs:
  repo:
    description: The repository to push the image to
    value: ${{ steps.set-env.outputs.repo }}
  image:
    description: The image name
    value: ${{ steps.set-env.outputs.image }}