name: "Build and Deploy to Cloud Run"

on:
  workflow_call:
    inputs:

      repo:
        required: true
        type: string

      image:
        required: true
        type: string
      
      tag:
        required: false
        type: string
        default: latest
      
      region:
        required: false
        type: string
        default: us-central1
      
      registry:
        required: false
        type: string
        default: us-docker.pkg.dev
    
    secrets:
      service_account:
        required: true
      
      workload_identity_provider:
        required: true
      
      project_id:
        required: true

env:
  PROJECT_ID: ${{ secrets.project_id }}
  REGION: ${{ inputs.region }}
  REPO: ${{ inputs.repo }}
  IMAGE: ${{ inputs.image }}
  DOCKER_TAG: ${{ inputs.tag }}
  REGISTRY: ${{ inputs.registry }}

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: GCP authentication
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.service_account }}
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
      
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref }}-
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.DOCKER_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REF=${{ github.ref }}
      
      - name: Deploy Cloud Run Revision
        run: |-
          gcloud run deploy ${{ env.IMAGE }} \
            --image ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.DOCKER_TAG }} \
            --region ${{ env.REGION }}