name: "Build and Deploy to Cloud Run"

on:
  workflow_call:
    inputs:

      PROJECT_ID:
        required: true
        type: string
      
      REGION:
        required: false
        type: string
        default: us-central1
      
      REPO:
        required: true
        type: string
      
      IMAGE:
        required: true
        type: string
      
      DOCKER_TAG:
        required: false
        type: string
        default: latest
      
      REGISTRY:
        required: false
        type: string
        default: us-docker.pkg.dev

      REF:
        required: true
        type: string
      
      SHA:
        required: true
        type: string

env:
  PROJECT_ID: ${{ inputs.PROJECT_ID }}
  REGION: ${{ inputs.REGION }}
  REPO: ${{ inputs.REPO }}
  IMAGE: ${{ inputs.IMAGE }}
  DOCKER_TAG: ${{ inputs.DOCKER_TAG }}
  REGISTRY: ${{ inputs.REGISTRY }}
  REF: ${{ inputs.REF }}
  SHA: ${{ inputs.SHA }}

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: GCP authentication
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.REF }}-${{ env.SHA }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ env.REF }}-
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.DOCKER_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          build-args: |
            GITHUB_SHA=${{ env.SHA }}
            GITHUB_REF=${{ env.REF }}
      
      - name: Deploy Cloud Run Revision
        run: |-
          gcloud run deploy ${{ env.IMAGE }} \
            --image ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.DOCKER_TAG }} \
            --region ${{ env.REGION }}